Add --helm-chart opt to phenomenal-minikube.

diff --git a/minikube/phenomenal-minikube b/minikube/phenomenal-minikube
--- a/minikube/phenomenal-minikube
+++ b/minikube/phenomenal-minikube
@@ -110,26 +110,27 @@ function print_help {
 	echo
 	echo "Options:"
 	echo "   -a, --all-stages                        Run all stages."
-	echo "   -1, --stage-1                           Run stage 1."
-	echo "   -2, --stage-2                           Run stage 2."
-	echo "   -3, --stage-3                           Run stage 3."
+	echo "   -1, --stage-1                           Run stage 1: start Minikube."
+	echo "   -2, --stage-2                           Run stage 2: start Helm."
+	echo "   -3, --stage-3                           Run stage 3: Helm install."
 	echo "   -b, --build-galaxy-container            Build the Galaxy container. Implies --dev."
-	echo "       --cnt-glx-path           <path>     Set the path to the container-galaxy-k8s-runtime cloned repository. Can be set also through environment variable PHNMNK_CNT_GLX_PATH. Default value is $DFT_DEVELOPMENT_FOLDER."
+	echo "       --cnt-glx-path           PATH       Set the path to the container-galaxy-k8s-runtime cloned repository. Can be set also through environment variable PHNMNK_CNT_GLX_PATH. Default value is $DFT_DEVELOPMENT_FOLDER."
 	echo "   -d, --minikube-dashboard                Open the minikube dashboard in browser."
 	echo "   -D, --minikube-delete                   Delete minikube vm before starting."
 	echo "   -e, --dev                               Development mode. Use path set with --cnt-glx-path or PHNMNK_CNT_GLX_PATH env var, to find Galaxy configuration to use and Galaxy tools to install."
 	echo "   -g, --debug                             Debug mode."
-	echo "       --glx-admin-email        <email>    Set the email for administrator account in Galaxy. Can be set also through environment variable PHNMNK_GLX_ADMIN_EMAIL. Default value is $DFT_GALAXY_ADMIN_EMAIL."
-	echo "       --glx-admin-password     <pass>     Set the password for administrator account in Galaxy. Can be set also through environment variable PHNMNK_GLX_ADMIN_PASSWORD. Default value is $DFT_GALAXY_ADMIN_PASSWORD."
-	echo "       --glx-api-key            <token>    Set the API key to connect to Galaxy. Can be set also through environment variable PHNMNK_GLX_API_KEY. Default value is $DFT_GALAXY_API_KEY."
+	echo "       --glx-admin-email        EMAIL      Set the email for administrator account in Galaxy. Can be set also through environment variable PHNMNK_GLX_ADMIN_EMAIL. Default value is $DFT_GALAXY_ADMIN_EMAIL."
+	echo "       --glx-admin-password     PASS       Set the password for administrator account in Galaxy. Can be set also through environment variable PHNMNK_GLX_ADMIN_PASSWORD. Default value is $DFT_GALAXY_ADMIN_PASSWORD."
+	echo "       --glx-api-key            TOKEN      Set the API key to connect to Galaxy. Can be set also through environment variable PHNMNK_GLX_API_KEY. Default value is $DFT_GALAXY_API_KEY."
 	echo "       --glx-18.01                         Configure for Galaxy 18.01 with options \"$CNT_GLX_18_01\"."
 	echo "       --glx-develop                       Configure for develop branch of container-galaxy-k8s-runtime with options \"$CNT_GLX_DEVELOP_BRANCH\"."
-	echo "       --helm-chart-version     <version>  Set the Helm chart version to use."
+	echo "       --helm-chart             NAME       Set the Helm chart version to use. Default is $CHART."
+	echo "       --helm-chart-version     VERSION    Set the Helm chart version to use."
 	echo "       --run-glx-cnt-script                Use simplified_galaxy_stable_container_creation.sh script to build Galaxy container."
 	echo "   -h, --help                              Print this help message."
-	echo "   -i, --galaxy-image           <image>    Set the Docker Galaxy image to use."
+	echo "   -i, --galaxy-image           IMAGE      Set the Docker Galaxy image to use."
 	echo "   -l, --galaxy-logs                       Open stream to Galaxy logs."
-	echo "   -L, --galaxy-log-file        <filename> Set name of Galaxy log file."
+	echo "   -L, --galaxy-log-file        FILENAME   Set name of Galaxy log file."
 	echo "   -p, --port-forwarding                   Forward ports 30000 and 30700 from the virtual machine to the host."
 	echo "       --enable-postgres                   Enable Postgres in Galaxy."
 	echo "   -r, --rbac                              Enable RBAC."
@@ -165,6 +166,7 @@ function read_args {
 			--glx-develop)           set -- $1 $CNT_GLX_DEVELOP_BRANCH "${@:2}" ;;
 			--glx-18.01)             set -- $1 $CNT_GLX_18_01 "${@:2}" ;;
 			-h|--help)               print_help ; exit 0 ;;
+			--helm-chart)            CHART="$2" ; shift_count=2 ;;
 			--helm-chart-version)    CHART_VERSION="$2" ; shift_count=2 ;;
 			-i|--galaxy-image)       GALAXY_IMAGE="$2" ; shift_count=2 ;;
 			-l|--galaxy-logs)        GALAXY_LOGS=$YES ;;
@@ -281,8 +283,10 @@ check_helm() {
 
 function start_helm {
 
+#	[[ -d $HOME/.helm ]] && rm -r $HOME/.helm
 	helm init || error "Cannot initialize helm !"
 	helm repo add galaxy-helm-repo https://pcm32.github.io/galaxy-helm-charts || error "cannot set PhenoMeNal Helm repository."
+	helm repo update || error "Cannot update Helm repository."
 
 	# Wait for Tiller to be ready
 	info "Wait for Tiller to be ready..."
